function herbert_init
% Adds the paths needed by Herbert.
%
% In your startup.m, add the Herbert root path and call herbert_init, e.g.
%       addpath('c:\mprogs\herbert\herbert_core')
%       herbert_init
%
% Is PC and Unix compatible.

warning('HERBERT:old_init_script',['\n',...
'*** **************************************************************************** ***\n',...    
'*** You are running old Herbert (version 3) and  separate herbert_init function  ***\n',...
'*** at location:  %s.\n', ...
'*** It is likely that your Horace initialization script is outdated.             ***\n',...
'*** This may cause various compartibility problems between horace3 and horace4   ***\n', ...
'*** Modify your startup script removing all addpath and *_init commands,         ***\n', ...
'*** and add single  "horace_on" initalization command.                           ***\n', ...
'*** This command will initialize recommended version of Horace.                  ***\n', ...
'*** Alternatively, put in your startup horace3_on or horace4_on calls,           ***\n' ...
'*** if you prefere specific Horace version.                                      ***\n' ...
'*** Beware that horace3 will become obsolete in the nearest future.              ***\n' ...
'*** **************************************************************************** ***\n'],...    
fileparts(mfilename('fullpath')));

herbert3_init()
