function herbert_init
% Adds the paths needed by Herbert.
%
% This is outdated script which should not be used and left for
% compatibility with previous versions of Horace/separate Herbert
%
% Is PC and Unix compatible.

warning('HERBERT:old_init_script',['\n',...
    '*** **************************************************************************** ***\n',...
    '*** You are running old Herbert (version 3) and  separate herbert_init function  ***\n',...
    '*** at location:  %s.\n', ...
    '*** It is likely that your Horace initialization script is outdated.             ***\n',...
    '*** This may cause various compatibility problems between horace3 and horace4    ***\n', ...
    '*** Modify your startup script removing all addpath and *_init commands,         ***\n', ...
    '*** and add single  "horace_on" initialization command.                          ***\n', ...
    '*** This command will initialize recommended version of Horace.                  ***\n', ...
    '*** Alternatively, put in your startup horace3_on or horace4_on calls,           ***\n' ...
    '*** if you prefer specific Horace version.                                       ***\n' ...
    '*** Beware that horace3 will become obsolete in the nearest future.              ***\n' ...
    '*** **************************************************************************** ***\n'],...
    fileparts(mfilename('fullpath')));

herbert3_init()
